### ISSUE TITLE
Please support node 4

### ISSUE THREAD

**Issue by sudo-suhas** [ttmarek/consolemock#7]
Hey, I just cloned `consolemock` and ran the check on node `v4.0.0` and it was successful. Do you mind adding support for node 4? We want to use this module in `lint-staged` for snapshot testing with jest. But we support node 4.2 and above and hence the request. If it is as simple as changing the `engines.node` field in the `package.json` and `circle.yml`, I could make a PR if you'd prefer it.

**Comment by ttmarek** [comment]
Hi @sudo-suhas!

Sure, we can support node 4. I don't think I'm using any features that aren't available in Node 4. The only question mark I have is `Array.prototype.fill`. Could you run a check to make sure nested groups work if you haven't already?

And YES! I would love to accept a PR. 💯 :1st_place_medal:

**Comment by sudo-suhas** [comment]
Thanks @ttmarek!

`Array.prototype.fill` is not a problem:
```
λ node
> process.versions.node
'4.0.0'
> [1, 2, 3].fill(1)
[ 1, 1, 1 ]
```
> Could you run a check to make sure nested groups work

`yarn run check` was successful. Is there anything else I would need to test?

> And YES! I would love to accept a PR. 💯 🥇

I'll make a PR for this tomorrow 😄

**Comment by sudo-suhas** [comment]
@ttmarek I was going through the source and it seems possible to make this module work without babel. Would you prefer that I refactor to remove the babel dependency while making it compatible with node 4? The only 2 features that I could see was destructuring(`const { prop } = obj`) and rest-spread(`...args`). Both can be achieved with a little bit extra work.

**Comment by ttmarek** [comment]
Hey @sudo-suhas. What benefit do we gain from getting rid of Babel?

**Comment by sudo-suhas** [comment]
Here's a blogpost which discusses this - http://davidtheclark.com/lessons-i-may-have-learned/

> Many times I’ve regretted the early decision to write stylelint in ES2015, compiling with Babel. It introduced various complexities, tooling incompatibilities, bug-sources, and other slight burdens that could have been entirely avoided. And for what payoff? For sugary syntax changes that are nice enough but definitely not necessary. (The really helpful stuff, like new data structures, can be polyfilled without compilation).

The advantages:
- No transpilation/build step
- Less dev dependencies to install
- The code _you_ write what the user gets. This makes stack traces much more usable. It also means if a user faces an issue, looking at the source will be a less jarring experience.

Considering that this project does not depend heavily on babel for compatibility with node 4, I would say it is better to not use babel.

**Comment by ttmarek** [comment]
@sudo-suhas. 
Hmm. I'll have to think about it. Thanks for the interest in making the consolemock better. Lets be lean about this...what do you say we try and tackle one problem at a time? First, lets add support for Node 4. Then we'll see about Babel. Is that cool?

**Comment by sudo-suhas** [comment]
Sure @ttmarek.

**Comment by ttmarek** [comment]
@sudo-suhas Thanks again. I published a new version with your changes (v0.2.2). Let me know how it goes.

**Comment by sudo-suhas** [comment]
Thanks @ttmarek! 

I have a couple of observations:
- `prepublish` script is deprecated:
  ```
  npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
  npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
  npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
  ```
  I think you can switch to [`prepublishOnly`](https://iamakulov.com/notes/npm-4-prepublish/)
- If you decide to continue with babel, it would be better to use [`babel-preset-env`](https://github.com/babel/babel-preset-env) than `babel-preset-latest` which [is deprecated](https://babeljs.io/docs/plugins/preset-latest/).

If you decide to remove babel, let me know. I'd be happy to make a PR.

**Comment by ttmarek** [comment]
Awesome, I'll let you know. Great tips!
